# Generated by Django 3.1.1 on 2020-10-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201012_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ART', 'Art'), ('CLT', 'Clothing & Accessories'), ('ELE', 'Electronics'), ('HME', 'Home'), ('KIT', 'Kitchen'), ('ENT', 'Entertainment'), ('TOY', 'Toys & Games'), ('SPT', 'Sports & Outdoors')], max_length=50),
        ),
    ]
